### ISSUE TITLE
TXTruthLensSelector

### ISSUE THREAD

**Issue by jpratmarti** [LSSTDESC/TXPipe#111]
Is this option necessary in the TXTruthLensSelector stage? or will we always want to use truez? Also, currently it is raising an error since this option is not defined. 
https://github.com/LSSTDESC/TXPipe/blob/51076382caab4c72508fd96b1eb39c69199fadb6/txpipe/lens_selector.py#L263

It is also happening in the TXSourceSelector stage.

[I'm starting a new branch to run no_shape_noise and fixing these things there, so I can push them there if useful.]

**Comment by joezuntz** [comment]
@ellongley could you have a think about this?

**Comment by ellongley** [comment]
Hi @jpratmarti I think you're right it's not necessary here since we have the TXMeanLensSelector stage.

**Comment by jpratmarti** [comment]
Ok, thanks both! I will remove the option then in the shape_noise branch.

**Comment by ellongley** [comment]
By the way - what would be the best way to add more specific logic for the apply_redshift_cut function?  Can we import a more general cut from the .yml file? I'm thinking for example of KiDS where we want to bin lower<zB ≤upper vs. lower≤=z<upper.   But also maybe there is a way to extend this class to take more general input binning logic rather than have it hardcoded for specific cuts as it is in select_lens now?

**Comment by joezuntz** [comment]
This is merged now, so I'll close this issue.
