### ISSUE TITLE
Using MPI in TreeCorr

### ISSUE THREAD

**Issue by joezuntz** [LSSTDESC/TXPipe#168]
To use TreeCorr's MPI facilities we need to make a change to how the shear catalog is stored.

To work in the distributed mode, all the processes need to create the same catalog and processing (gg etc) objects, and then pass the communicator to `gg.process`.  

In MPI + low-memory mode, each process reads the patches it is (currently) using from disc separately, and then frees them.  This won't work if they're already loaded into memory by TXPipe, and passed as numpy arrays, as they are now (so that we can load everything once and then do the splitting into tomographic bins + calibration).

To make this work we can introduce an intermediate stage which splits the shear catalog into bins and calibrates the values.  It will save each bin into a different column of a new `calibrated_shear_catalog.hdf5` file.  That way TreeCorr can access these columns directly as there is no additional pre-processing to be done.

The other advantage here is that we avoid making unnecessary copies of columns.

@rmjarvis - have I understood TreeCorr correctly here?
@anicola and @fjaviersanchez, does this work for the HSC pipelines also?
Also paging @ellongley as we've been discussing.

**Comment by rmjarvis** [comment]
The bits about MPI and low_mem are mostly right.  Certainly low_mem can't unload and reload the memory if you are working with Catalogs that are built from arrays, since there's no way to reload that.  But the MPI stuff should work fine with Catalogs built from arrays.  It's true though that all nodes should have all the same things loaded.  Until each node looks at all the data, there's no way for it to know which Catalogs are required for its part of the computation.  There is probably a semi-smart way to do that better, but so far my ideas for how to require less data to be (ever) loaded on each machine still require loading from files, not in-memory numpy arrays.  So it may not be helpful for your case.

Also, if you want, you don't have to create one huge Catalog and then split it into patches in TreeCorr.  If it's more convenient, you can make the separate patch catalogs yourself.  (And either write each one to disk in a separate file, or as you suggested a single HDF5 file with different columns.  Either should work.)  Then you can pass the list of Catalogs to `gg.process` rather than just one big catalog.  

This is kind of what the patch stuff is doing behind the scenes anyway.  So if you want more control about the patch creation steps, that might be an easier path to take.  If you go this route, just tell each Catalog which patch it corresponds to using the `patch` parameter, which you should give as a single integer.

**Comment by ellongley** [comment]
Hi @joezuntz, mentioning what we were discussing on Slack here, the HSC c1, c2 terms should be subtracted per object, (as they are in the non-parallel function, note the order of operations for m and R, Javi and Andrina can confirm). If we are going to subtract out a mean "c" term calculated from the data for DES and Kids here, (which currently lives in twopoint) then that should be a weighted average per bin (with only the objects selected per bin).

**Comment by fjaviersanchez** [comment]
I think that calibrating all galaxies in a given bin prior to feeding them to TreeCorr should be fine. This is effectively what we do when we generate the maps. As Emily mentions, the additive bias corrections are made in a per-galaxy basis (more details here: https://github.com/LSSTDESC/TXPipe/blob/HSC/txpipe/utils/calibration_tools.py#L126-L129) but I think that shouldn't prevent the generation of a calibrated catalog.
