### ISSUE TITLE
Plotting Stage shouldn't need the theory

### ISSUE THREAD

**Issue by jpratmarti** [LSSTDESC/TXPipe#218]
We should not require a theory output to plot the measurements. It should be an option.

**Comment by joezuntz** [comment]
I've had a look at this, and though it's easy to make inputs optional for individual stages, doing so greatly complicates writing automatic pipelines, because you can't tell which optional inputs will actually be generated until runtime.  I think an easier alternative is a mini-stage which is the same as the current plotting stage but doesn't need or use the theory. We can do that with a trivial subclass.

**Comment by joezuntz** [comment]
This was dealt with in PR #280
