### ISSUE TITLE
Easy Tasks

### ISSUE THREAD

**Issue by joezuntz** [LSSTDESC/TXPipe#25]
These tasks are fairly easy and a good place to start for a beginner.  Comment here or chat with @joezuntz if you're interested, or just give them a go.

- [x] Add options to twopoint stages to select which bin pairs to use
- [x] Tidy dictionary keys in covariances.py
- [x] Profiling speed of TXDiagnosticMaps with number of cores
- [ ] Investigate lens selection settings (CMASS & LOWZ) to suit this data
- [x] Write single script to generate a suite of plots from the full set of outputs

**Comment by ih64** [comment]
Hi @joezuntz, just beginning to take a crack at the first bullet point. I was considering adding a 'lens_bins' and 'source_bins' options to the TXTwoPoint in the config.yaml, that expect lists. if the lists are empty, txpipe would just run all available bin pairs.  otherwise, some quick checks to make sure that the bins exist in the tomography file, and run those pairs in particular. does that sound ok?

**Comment by joezuntz** [comment]
@ih64 - great, sounds good!  I think you may have to make the type a string and parse it.

**Comment by joezuntz** [comment]
We now have redmagic lenses so the last missing task here is no longer needed.
