### ISSUE TITLE
Medium Tasks

### ISSUE THREAD

**Issue by joezuntz** [LSSTDESC/TXPipe#26]
These are tasks of medium difficulty.  If you're interested then please have a go, and/or chat with @joezuntz .

- [x] Choose and test pixel sizes and ell ranges for DC2
- [x] Final pieces of covariance code - store results along with 2pt and n(z)
- [x] Adding metacalibration m factors to Fourier two point code
- [x] Improving mask code in mapper
- [x] Add truth data (when available) into input_cats

**Comment by damonge** [comment]
Happy to look at masks (or anything related to mapping)

**Comment by joezuntz** [comment]
@damonge - cool, that would be brilliant.  The existing masking code is a trivial function in sysmaps.py, called compute_mask.  Right now it's just 1.0 wherever there is any depth measured whatsoever.  I've passed it in the depth_count variable right now, which is just the number of objects measured in each point, but it might want various other inputs instead.  Any thoughts on how to do this?

Anything on the rest of the maps code would also be vvv useful. Most of it is done in the utils/basic_maps.py file

**Comment by damonge** [comment]
What is depth_count here? Is it a depth map (as in, X-sigma magnitude limit in different pixels)?
That one is not easy to translate into what we want for the mask, which is essentially a completeness map. 

Is there any masking information in the DC2 data? (e.g. any fake bright-object mask flag or something like that?). That'd be what one would use to create the mask to begin with, essentially tracking the fractional area of a given pixel that is reliable.

I can try to look into what's available in the data. Is there someone who has already familiarized themselves with it that I could ask?

**Comment by joezuntz** [comment]
depth_count is actually just the number of objects that went into the depth mask, so even less useful than that.  The depth map, which is an x-sigma limit (configurable what x is) is there too, but sounds like that's not what you want.  Right now we're using CosmoDC2, which doesn't have any masking info at all, but we hope soon to switch to something that's actually processed images via the object catalog.  We're waiting on the input data for that, though.  Once we get that, what kind of quantities would you need?  @cwwalter might be good to ask on data contents.

**Comment by damonge** [comment]
OK, great.

Minimally, we'd want flags attached to each object that should be masked (because it's close to an artifact/bright star etc.). Ideally we'd like to have maps in some form of pixellization that can say, for a given point in the sky, whether it's been observed or not, whether it should be masked because of bright objects/saturated pixels/whatever.

I understand the latter hasn't even been attempted by DM yet, but we had information on the former in the HSC data, so I wonder if there is (or will be) something like that in DC2.
We can start with a minimal approach where we assume that those flags will be there. If they aren't, the information isn't used, and the mask is simply counts-based. It'd be good to hear @cwwalter 's thoughts, though

**Comment by joezuntz** [comment]
The other good place to discuss is #desc-dc2-users on slack.
