### ISSUE TITLE
Covariance storage format

### ISSUE THREAD

**Issue by joezuntz** [LSSTDESC/TXPipe#6]
We'd like the format for the covariance matrix to be explicit.

Maybe something like and HDF5 file with:

```
/cov/index/type1 - integer array length N - indicator of data type1 (xip, xim, gammat, wtheta, C_ell_g etc) of corresponding 
/cov/index/type2 - integer array length N - indicator of data type2 (xip, xim, gammat, wtheta, etc) of corresponding index
/cov/index/tomobin1 - integer array length N - tomo bin 1 of corresponding index
/cov/index/tomobin2 - integer array length N - tomo bin 2 of corresponding index
/cov/index/angbin1 - integer array length N - angular bin 1 of corresponding index
/cov/index/angbin2 - integer array length N - angular bin 1 of corresponding index
/cov/covmat - double array N*N - actual matrix
```

So that to work out the meaning of covmat[i,j] you would just have to look at the i'th and j'th values in the index arrays to tell you what pair of values are being used.

**Comment by damonge** [comment]
I believe SACC supports covariances, and has functionality to do some or all of this, so it may be good to have @slosar in the loop

**Comment by joezuntz** [comment]
Yep - I think this is before we have a data vector to go along with it.  Will SACC cope with that @slosar ? Or we could always put in a mock (all zero) data vector and use the same format.

**Comment by slosar** [comment]
So, SACC has exactly this functionality (if I understand you correctly). It has the concept of "binning" (for lack of better word), which is essentially a list of rows, where row i (=0..N-1) explains what the index i means (i.e. tracer id, tomographic bin, nominal ell (or separation) window function, etc). Then there is the mean vector of size N and a matrix of size NxN. After much discussion, we decided to store the *precision matrix* instead, i.e. C^{-1} and not C. This is because any code would inevitably first invert it and why wast time when the matrix becomes large. It can be stored as diagonal, block diagonal or dense. sacc the writes is as a dataset into sacc file or it can refer to an external file with cov matrix (a typical use is when you have 100 mocks that share the same theoretical covariance matrix). Do you need anything else?

I was supposed to document all this much better, but I always get distracted by other things.  How do you want to proceed here?

**Comment by joezuntz** [comment]
Okay, that sounds like it should work - do the sacc tools to create these things work right now?

We shouldn't be storing the precision matrix - very often (basically always) you want to do a variety of  different scale cuts on the data before using it.  So if you store the prec matrix you have to invert it, then cut it, then invert it again, wasting even more time.

**Comment by slosar** [comment]
That is a good point. I can add this functionality (storing covariance matrix rather than precision and making sure they don't get confused) and making sure it will take `None` as the mean vector. Then I can give you an example that writes/reads a covariance matrix alone. Makes sense?

**Comment by joezuntz** [comment]
That's perfect, thanks!

**Comment by slosar** [comment]
No worries. I'll move it to your repo as soon as I find a time for a breather.
But, I thought that this was already done during the Oxford hack session, no?
