### ISSUE TITLE
DIR N(z) calibration

### ISSUE THREAD

**Issue by damonge** [LSSTDESC/TXPipe#99]
Implement a color-weighting-based N(z) estimation stage. This would minimally require two things:
- The possibility of taking in an external catalog with spec-zs and fluxes. One issue is that the same cuts should be performed on this catalog as in the data, so this may be something that needs to be taken in at the sample selection stage (or not).
- Writing a quick kd-tree based method to estimate color-space weights (a la [this](https://github.com/LSSTDESC/DEHSC_LSS/blob/master/hsc_lss/cosmos_weight.py)). A SOM-based method would be even better, but this is an easy first step. Use those weights to get an N(z) from the spec-zs.

**Comment by AngusWright** [comment]
I will happily help with this, as I've been meaning to get involved in the DESC calibration effort for a while. This seems like a good opportunity to join in! 

I'd be happy to implement my full SOM calibration pipeline, but fair warning that it is R code. There are nice integration wrappers between python and R (and vice versa) so we should be able to interface the scripts pretty easily, if that's of interest. Otherwise we can implement the same procedures using the available Python libraries (most of the relevant functionality of R's kohonen package seems present in python's MiniSOM, for example). This will of course take more time, though.

**Comment by MBilicki** [comment]
A publicly-available kind of DIR implementation is within the ANNz2 package by Sadeh et al. I have it working on my side so can help with generating some at least first-step N(z)s this way.

What do you mean by saying "the same cuts should be performed on this catalog as in the data" - cuts in magnitude space?

**Comment by aimalz** [comment]
Sorry for failing to join the discussion when it was still fresh!  This is kind of the core of PZCalibrate, whose scope [has expanded](https://github.com/LSSTDESC/Science_Roadmap/tree/pz-refactoring) to include any and all competitive N(z) estimation techniques.  If TXPipe integration is to any degree a barrier to getting this running in the context of DESC, please consider making an issue with a link to the code in question (any language!) in [the old PZCalibrate repo](https://github.com/LSSTDESC/pz_calibrate/issues).  Though it's due for an overall tune-up, the goal of the pipeline is to not only estimate N(z) for TXPipe ingestion but to enable an autonomous benchmarking test of multiple N(z) estimators (under a variety of assumptions, of course, but the specifics of cuts, etc. are experimental design choices unrelated to the infrastructure in this case) on the increasingly realistically complex mock data from PZIncomplete/RAIL.  The hope is that this will reduce the overhead for those contributing PZCalibrate back-end algorithms, as the TXPipe integration can happen at the level of a wrapper class for all N(z) estimators rather than for each approach as an independent module.  Point being, if you have code for this, please consider working on it from the PZ side so we have something around which to build up the flexible infrastructure that we need anyway.
